//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.

//Example 1:
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.

//Example 2:
//Input: s = "", t = "y"
//Output: "y"

//Reverse Hashset: add t to s and remove duplicates as they fail to get added, only letter left will be added letter

string s = "abcd";
string t = "acdbe"; //Shuffled s and edded e

HashSet<char> additonalChar = new(s);

foreach (char c in t)
{
    if(!additonalChar.Add(c)) //HashSet.Add() is a boolean method that returns true if value was added, and false if value is already present
    {
        additonalChar.Remove(c);
    }
}

Console.WriteLine($"the added character is: {string.Join("", additonalChar)}");